spring:
  datasource:
    url: jdbc:mysql://adopet.colekckgvkoc.us-east-1.rds.amazonaws.com:3306/adopet?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
    username: admin
    password: 8uk6kwqi
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true